// This file is automatically generated by gen-router.js, please do not modify it manually！
import VueRouter from 'vue-router'
import Vue from 'vue'

Vue.use(VueRouter)

const routes = [
  {
    path: '/fullscreen',
    name: 'fullscreen',
    meta: { description: '全屏切换方案' },
    component: () => import(/* webpackChunkName: "fullscreen" */ '@/views/fullscreen.vue'),
  },
  {
    path: '/guide',
    name: 'guide',
    meta: { description: 'driver.js demo' },
    component: () => import(/* webpackChunkName: "guide" */ '@/views/guide.vue'),
  },
  {
    path: '/',
    name: 'home',
    meta: { description: '首页' },
    component: () => import(/* webpackChunkName: "home" */ '@/views/home.vue'),
  },
  {
    path: '/icons',
    name: 'icons',
    meta: { description: 'icon 使用范例' },
    component: () => import(/* webpackChunkName: "icons" */ '@/views/icons.vue'),
  },
]

const router = new VueRouter({
  mode: 'hash',
  routes,
})

router.afterEach((to) => {
  document.title = `${to.meta?.description} - VUE-EL-DEMO`
})

export default router
