// This file is automatically generated by gen-router.js, please do not modify it manually！
import VueRouter from 'vue-router'
import Vue from 'vue'

Vue.use(VueRouter)

const routes = [
  {
    path: '/',
    name: 'home',
    meta: { description: '首页' },
    component: () => import(/* webpackChunkName: "home" */ '@/views/home'),
  },
  {
    path: '/dashboard/index',
    name: 'dashboardIndex',
    meta: { description: '拖拽式仪表盘' },
    component: () => import(/* webpackChunkName: "dashboardIndex" */ '@/views/dashboard/index'),
  },
  {
    path: '/fullscreen',
    name: 'fullscreen',
    meta: { description: '全屏切换方案' },
    component: () => import(/* webpackChunkName: "fullscreen" */ '@/views/fullscreen'),
  },
  {
    path: '/guide',
    name: 'guide',
    meta: { description: 'driver.js demo' },
    component: () => import(/* webpackChunkName: "guide" */ '@/views/guide'),
  },
  {
    path: '/icons',
    name: 'icons',
    meta: { description: 'icon 使用范例' },
    component: () => import(/* webpackChunkName: "icons" */ '@/views/icons'),
  },
  {
    path: '/minder-editor',
    name: 'minderEditor',
    meta: { description: '脑图编辑器 demo' },
    component: () => import(/* webpackChunkName: "minderEditor" */ '@/views/minder-editor'),
  },
  {
    path: '/set-height-adaptive',
    name: 'setHeightAdaptive',
    meta: { description: 'v-height-adaptive 高度自适应的表格' },
    component: () => import(/* webpackChunkName: "setHeightAdaptive" */ '@/views/set-height-adaptive'),
  },
  {
    path: '/sticky-fixed-col',
    name: 'stickyFixedCol',
    meta: { description: 'v-sticky-header 固定列表格' },
    component: () => import(/* webpackChunkName: "stickyFixedCol" */ '@/views/sticky-fixed-col'),
  },
  {
    path: '/sticky-scroller',
    name: 'stickyScroller',
    meta: { description: 'v-sticky-scroller 固定横向滚动条' },
    component: () => import(/* webpackChunkName: "stickyScroller" */ '@/views/sticky-scroller'),
  },
  {
    path: '/sticky-sum',
    name: 'stickySum',
    meta: { description: 'v-sticky-footer 表尾合计行' },
    component: () => import(/* webpackChunkName: "stickySum" */ '@/views/sticky-sum'),
  },
]

const router = new VueRouter({
  mode: 'hash',
  routes,
})

router.afterEach((to) => {
  document.title = `${to.meta?.description} - VUE-EL-DEMO`
})

export default router
